// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package SQLC

import (
	"database/sql"
)

type Order struct {
	ID              string
	Price           float64
	Tax             float64
	FinalPrice      float64
	IssueDate       sql.NullTime
	TypeRequisition string
	DeleteAt        sql.NullTime
}
