// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type NewOrder struct {
	Price     float64   `json:"price"`
	Tax       float64   `json:"tax"`
	IssueDate time.Time `json:"issueDate"`
}

type Order struct {
	ID              string     `json:"id"`
	Price           float64    `json:"price"`
	Tax             float64    `json:"tax"`
	FinalPrice      float64    `json:"finalPrice"`
	IssueDate       time.Time  `json:"issueDate"`
	TypeRequisition string     `json:"typeRequisition"`
	DeleteAt        *time.Time `json:"deleteAt,omitempty"`
}

type Query struct {
}
