// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/JeanCarlos20-code/CleanArchitecture/internal/controller/web"
	"github.com/JeanCarlos20-code/CleanArchitecture/internal/core/repositories"
	"github.com/JeanCarlos20-code/CleanArchitecture/internal/core/use-cases/order"
	"github.com/JeanCarlos20-code/CleanArchitecture/internal/event"
	"github.com/JeanCarlos20-code/CleanArchitecture/internal/infra/database"
	"github.com/JeanCarlos20-code/CleanArchitecture/internal/infra/database/SQLC"
	"github.com/JeanCarlos20-code/CleanArchitecture/pkg/events"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *order.CreateOrderUseCase {
	queries := ProvideSQLCQueries(db)
	orderRepository := database.NewOrderRepository(db, queries)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := order.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewListOrderUseCase(db *sql.DB) *order.ListOrderUseCase {
	queries := ProvideSQLCQueries(db)
	orderRepository := database.NewOrderRepository(db, queries)
	listOrderUseCase := order.NewListOrderUseCase(orderRepository)
	return listOrderUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.WebOrderHandler {
	queries := ProvideSQLCQueries(db)
	orderRepository := database.NewOrderRepository(db, queries)
	orderCreated := event.NewOrderCreated()
	webOrderHandler := web.NewWebOrderHandler(eventDispatcher, orderRepository, orderCreated)
	return webOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(repositories.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))

func ProvideSQLCQueries(db *sql.DB) *SQLC.Queries {
	return SQLC.New(db)
}
